version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: pip install "tensorflow<1.14"
          name: Install TensorFlow
      - run:
          command: pip install .[tests]
          name: Install the library
      - run:
          command: pytest tests
          name: Tests         
workflows:
  main:
    jobs:
      - build-and-test
