version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.4

jobs:
  build-and-test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y wget libsndfile-dev libsox-fmt-mp3 sox
      - run:
          command: pip install "tensorflow<1.14"
          name: Install TensorFlow
      - run:
          command:  pip install 'h5py==2.10.0' --force-reinstall
          name: Reinstall h5py                
      - run:
          command: pip install .[tests]
          name: Install the library   
      - run:
          command: pytest --cov-report term-missing --cov-report=xml --cov dcase_models ./tests
          name: Tests    
      - codecov/upload:
          file: coverage.xml          
workflows:
  main:
    jobs:
      - build-and-test
